### ISSUE TITLE
Missing .js file(s).

### ISSUE THREAD

**Issue by lalibi** [tparnell8/TurboLinks.Net#3]
Example project misses several assets (`.js`, `.css` files and images). I think at least one `.js` file should be present in order for the example to work.

**Comment by TerribleDev** [comment]
Thanks, I think when I ported this from rc2 to 1.0.0 I remember redoing some of the js/html, and I think they were accidentally removed.

They should be there now.

**Comment by TerribleDev** [comment]
oh I didnt bother adding back the images
